# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e208184dcdf66692866381b83014990192561c6f74345fc2833a1ae75ff8f36a17357c249b5f0a40d67400fdf1f08015d92ee1ec2bd85e14c700b4678d7373e0

test:
  secret_key_base: 8a312941ebecbbdc6251c144540ea93b44eaab13eff00610031dce7941a51df144f9622d86bdb883152f4436fda8d1bb0b902b37a6749847e22832363497f2ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
